services:
  ota-api:
    restart: unless-stopped
  ota-worker:
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  rabbitmq:
    restart: unless-stopped
  ota-console:
    restart: unless-stopped
