// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type TAuditLog struct {
	ID            int64                 `json:"id"`
	TraceID       string                `json:"trace_id"`
	Operator      string                `json:"operator"`
	OperationType string                `json:"operation_type"`
	ResourceID    string                `json:"resource_id"`
	BeforeState   pqtype.NullRawMessage `json:"before_state"`
	AfterState    pqtype.NullRawMessage `json:"after_state"`
	CreatedAt     time.Time             `json:"created_at"`
}

type TDevice struct {
	DeviceID        string          `json:"device_id"`
	DeviceGroup     string          `json:"device_group"`
	ProductModel    string          `json:"product_model"`
	HardwareVersion string          `json:"hardware_version"`
	CurrentVersion  string          `json:"current_version"`
	LastHeartbeat   time.Time       `json:"last_heartbeat"`
	ProductCode     string          `json:"product_code"`
	Tags            json.RawMessage `json:"tags"`
	RegisteredAt    time.Time       `json:"registered_at"`
}

type TIdempotency struct {
	IdemKey   string          `json:"idem_key"`
	Response  json.RawMessage `json:"response"`
	CreatedAt time.Time       `json:"created_at"`
}

type TPackage struct {
	PackageID            string       `json:"package_id"`
	ProductCode          string       `json:"product_code"`
	Version              string       `json:"version"`
	FileHash             string       `json:"file_hash"`
	Signature            string       `json:"signature"`
	Status               string       `json:"status"`
	CreatedAt            time.Time    `json:"created_at"`
	FileSize             int64        `json:"file_size"`
	Name                 string       `json:"name"`
	HardwareVersionMin   string       `json:"hardware_version_min"`
	HardwareVersionMax   string       `json:"hardware_version_max"`
	MinUpgradableVersion string       `json:"min_upgradable_version"`
	DependsOnVersion     string       `json:"depends_on_version"`
	PublishTime          sql.NullTime `json:"publish_time"`
}

type TReleaseTask struct {
	TaskID           string       `json:"task_id"`
	PackageID        string       `json:"package_id"`
	TargetGroup      string       `json:"target_group"`
	ProductModel     string       `json:"product_model"`
	HardwareVersion  string       `json:"hardware_version"`
	FailureThreshold string       `json:"failure_threshold"`
	State            string       `json:"state"`
	CreatedAt        time.Time    `json:"created_at"`
	CanaryPercent    int32        `json:"canary_percent"`
	ScheduleTime     sql.NullTime `json:"schedule_time"`
	ForceUpgrade     bool         `json:"force_upgrade"`
}

type TTaskStat struct {
	ID                int64           `json:"id"`
	TaskID            string          `json:"task_id"`
	TotalCount        int32           `json:"total_count"`
	SuccessCount      int32           `json:"success_count"`
	FailedCount       int32           `json:"failed_count"`
	FailureRate       string          `json:"failure_rate"`
	ErrorDistribution json.RawMessage `json:"error_distribution"`
	SnapshotTime      time.Time       `json:"snapshot_time"`
}

type TUpgradeRecord struct {
	ID            int64     `json:"id"`
	DeviceID      string    `json:"device_id"`
	TaskID        string    `json:"task_id"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	SourceVersion string    `json:"source_version"`
	TargetVersion string    `json:"target_version"`
	ErrorCode     string    `json:"error_code"`
}
