// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ota.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM t_device
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPackages = `-- name: CountPackages :one
SELECT COUNT(*) FROM t_package
`

func (q *Queries) CountPackages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO t_audit_log (
  trace_id,
  operator,
  operation_type,
  resource_id,
  before_state,
  after_state
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, trace_id, operator, operation_type, resource_id, before_state, after_state, created_at
`

type CreateAuditLogParams struct {
	TraceID       string                `json:"trace_id"`
	Operator      string                `json:"operator"`
	OperationType string                `json:"operation_type"`
	ResourceID    string                `json:"resource_id"`
	BeforeState   pqtype.NullRawMessage `json:"before_state"`
	AfterState    pqtype.NullRawMessage `json:"after_state"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (TAuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.TraceID,
		arg.Operator,
		arg.OperationType,
		arg.ResourceID,
		arg.BeforeState,
		arg.AfterState,
	)
	var i TAuditLog
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Operator,
		&i.OperationType,
		&i.ResourceID,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}

const createIdempotency = `-- name: CreateIdempotency :one
INSERT INTO t_idempotency (
  idem_key,
  response
) VALUES (
  $1, $2
)
ON CONFLICT (idem_key)
DO UPDATE SET idem_key = t_idempotency.idem_key
RETURNING idem_key, response, created_at
`

type CreateIdempotencyParams struct {
	IdemKey  string          `json:"idem_key"`
	Response json.RawMessage `json:"response"`
}

func (q *Queries) CreateIdempotency(ctx context.Context, arg CreateIdempotencyParams) (TIdempotency, error) {
	row := q.db.QueryRowContext(ctx, createIdempotency, arg.IdemKey, arg.Response)
	var i TIdempotency
	err := row.Scan(&i.IdemKey, &i.Response, &i.CreatedAt)
	return i, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO t_package (
  package_id,
  product_code,
  version,
  file_hash,
  signature,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING package_id, product_code, version, file_hash, signature, status, created_at
`

type CreatePackageParams struct {
	PackageID   string `json:"package_id"`
	ProductCode string `json:"product_code"`
	Version     string `json:"version"`
	FileHash    string `json:"file_hash"`
	Signature   string `json:"signature"`
	Status      string `json:"status"`
}

type CreatePackageRow struct {
	PackageID   string    `json:"package_id"`
	ProductCode string    `json:"product_code"`
	Version     string    `json:"version"`
	FileHash    string    `json:"file_hash"`
	Signature   string    `json:"signature"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (CreatePackageRow, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.PackageID,
		arg.ProductCode,
		arg.Version,
		arg.FileHash,
		arg.Signature,
		arg.Status,
	)
	var i CreatePackageRow
	err := row.Scan(
		&i.PackageID,
		&i.ProductCode,
		&i.Version,
		&i.FileHash,
		&i.Signature,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createReleaseTask = `-- name: CreateReleaseTask :one
INSERT INTO t_release_task (
  task_id,
  package_id,
  target_group,
  product_model,
  hardware_version,
  failure_threshold,
  state
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING task_id, package_id, target_group, product_model, hardware_version, failure_threshold, state, created_at
`

type CreateReleaseTaskParams struct {
	TaskID           string `json:"task_id"`
	PackageID        string `json:"package_id"`
	TargetGroup      string `json:"target_group"`
	ProductModel     string `json:"product_model"`
	HardwareVersion  string `json:"hardware_version"`
	FailureThreshold string `json:"failure_threshold"`
	State            string `json:"state"`
}

type CreateReleaseTaskRow struct {
	TaskID           string    `json:"task_id"`
	PackageID        string    `json:"package_id"`
	TargetGroup      string    `json:"target_group"`
	ProductModel     string    `json:"product_model"`
	HardwareVersion  string    `json:"hardware_version"`
	FailureThreshold string    `json:"failure_threshold"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) CreateReleaseTask(ctx context.Context, arg CreateReleaseTaskParams) (CreateReleaseTaskRow, error) {
	row := q.db.QueryRowContext(ctx, createReleaseTask,
		arg.TaskID,
		arg.PackageID,
		arg.TargetGroup,
		arg.ProductModel,
		arg.HardwareVersion,
		arg.FailureThreshold,
		arg.State,
	)
	var i CreateReleaseTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.PackageID,
		&i.TargetGroup,
		&i.ProductModel,
		&i.HardwareVersion,
		&i.FailureThreshold,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT device_id, device_group, product_model, hardware_version, current_version, product_code, last_heartbeat, tags, registered_at
FROM t_device
WHERE device_id = $1
`

type GetDeviceByIDRow struct {
	DeviceID        string          `json:"device_id"`
	DeviceGroup     string          `json:"device_group"`
	ProductModel    string          `json:"product_model"`
	HardwareVersion string          `json:"hardware_version"`
	CurrentVersion  string          `json:"current_version"`
	ProductCode     string          `json:"product_code"`
	LastHeartbeat   time.Time       `json:"last_heartbeat"`
	Tags            json.RawMessage `json:"tags"`
	RegisteredAt    time.Time       `json:"registered_at"`
}

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID string) (GetDeviceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, deviceID)
	var i GetDeviceByIDRow
	err := row.Scan(
		&i.DeviceID,
		&i.DeviceGroup,
		&i.ProductModel,
		&i.HardwareVersion,
		&i.CurrentVersion,
		&i.ProductCode,
		&i.LastHeartbeat,
		&i.Tags,
		&i.RegisteredAt,
	)
	return i, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT idem_key, response, created_at
FROM t_idempotency
WHERE idem_key = $1
`

func (q *Queries) GetIdempotency(ctx context.Context, idemKey string) (TIdempotency, error) {
	row := q.db.QueryRowContext(ctx, getIdempotency, idemKey)
	var i TIdempotency
	err := row.Scan(&i.IdemKey, &i.Response, &i.CreatedAt)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT package_id, product_code, version, file_hash, signature, status, created_at
FROM t_package
WHERE package_id = $1
`

type GetPackageByIDRow struct {
	PackageID   string    `json:"package_id"`
	ProductCode string    `json:"product_code"`
	Version     string    `json:"version"`
	FileHash    string    `json:"file_hash"`
	Signature   string    `json:"signature"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetPackageByID(ctx context.Context, packageID string) (GetPackageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPackageByID, packageID)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.PackageID,
		&i.ProductCode,
		&i.Version,
		&i.FileHash,
		&i.Signature,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseTaskByID = `-- name: GetReleaseTaskByID :one
SELECT task_id, package_id, target_group, product_model, hardware_version, failure_threshold, state, created_at
FROM t_release_task
WHERE task_id = $1
`

type GetReleaseTaskByIDRow struct {
	TaskID           string    `json:"task_id"`
	PackageID        string    `json:"package_id"`
	TargetGroup      string    `json:"target_group"`
	ProductModel     string    `json:"product_model"`
	HardwareVersion  string    `json:"hardware_version"`
	FailureThreshold string    `json:"failure_threshold"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetReleaseTaskByID(ctx context.Context, taskID string) (GetReleaseTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseTaskByID, taskID)
	var i GetReleaseTaskByIDRow
	err := row.Scan(
		&i.TaskID,
		&i.PackageID,
		&i.TargetGroup,
		&i.ProductModel,
		&i.HardwareVersion,
		&i.FailureThreshold,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskStats = `-- name: GetTaskStats :one
SELECT task_id, total_count, success_count, failed_count, failure_rate,
       error_distribution, snapshot_time
FROM t_task_stats
WHERE task_id = $1
ORDER BY snapshot_time DESC
LIMIT 1
`

type GetTaskStatsRow struct {
	TaskID            string          `json:"task_id"`
	TotalCount        int32           `json:"total_count"`
	SuccessCount      int32           `json:"success_count"`
	FailedCount       int32           `json:"failed_count"`
	FailureRate       string          `json:"failure_rate"`
	ErrorDistribution json.RawMessage `json:"error_distribution"`
	SnapshotTime      time.Time       `json:"snapshot_time"`
}

func (q *Queries) GetTaskStats(ctx context.Context, taskID string) (GetTaskStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskStats, taskID)
	var i GetTaskStatsRow
	err := row.Scan(
		&i.TaskID,
		&i.TotalCount,
		&i.SuccessCount,
		&i.FailedCount,
		&i.FailureRate,
		&i.ErrorDistribution,
		&i.SnapshotTime,
	)
	return i, err
}

const listAuditLogsByResource = `-- name: ListAuditLogsByResource :many
SELECT id, trace_id, operator, operation_type, resource_id, before_state, after_state, created_at
FROM t_audit_log
WHERE resource_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListAuditLogsByResource(ctx context.Context, resourceID string) ([]TAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TAuditLog{}
	for rows.Next() {
		var i TAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Operator,
			&i.OperationType,
			&i.ResourceID,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT device_id, device_group, product_model, hardware_version, current_version, product_code, last_heartbeat, tags, registered_at
FROM t_device
ORDER BY last_heartbeat DESC
LIMIT $1 OFFSET $2
`

type ListDevicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDevicesRow struct {
	DeviceID        string          `json:"device_id"`
	DeviceGroup     string          `json:"device_group"`
	ProductModel    string          `json:"product_model"`
	HardwareVersion string          `json:"hardware_version"`
	CurrentVersion  string          `json:"current_version"`
	ProductCode     string          `json:"product_code"`
	LastHeartbeat   time.Time       `json:"last_heartbeat"`
	Tags            json.RawMessage `json:"tags"`
	RegisteredAt    time.Time       `json:"registered_at"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesRow{}
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.DeviceGroup,
			&i.ProductModel,
			&i.HardwareVersion,
			&i.CurrentVersion,
			&i.ProductCode,
			&i.LastHeartbeat,
			&i.Tags,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingRunningTasks = `-- name: ListMatchingRunningTasks :many
SELECT task_id, package_id, target_group, product_model, hardware_version, failure_threshold, state, created_at
FROM t_release_task
WHERE state = 'Running'
  AND target_group = $1
  AND product_model = $2
  AND hardware_version = $3
ORDER BY created_at DESC
`

type ListMatchingRunningTasksParams struct {
	TargetGroup     string `json:"target_group"`
	ProductModel    string `json:"product_model"`
	HardwareVersion string `json:"hardware_version"`
}

type ListMatchingRunningTasksRow struct {
	TaskID           string    `json:"task_id"`
	PackageID        string    `json:"package_id"`
	TargetGroup      string    `json:"target_group"`
	ProductModel     string    `json:"product_model"`
	HardwareVersion  string    `json:"hardware_version"`
	FailureThreshold string    `json:"failure_threshold"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) ListMatchingRunningTasks(ctx context.Context, arg ListMatchingRunningTasksParams) ([]ListMatchingRunningTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listMatchingRunningTasks, arg.TargetGroup, arg.ProductModel, arg.HardwareVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchingRunningTasksRow{}
	for rows.Next() {
		var i ListMatchingRunningTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.PackageID,
			&i.TargetGroup,
			&i.ProductModel,
			&i.HardwareVersion,
			&i.FailureThreshold,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
SELECT package_id, product_code, version, file_hash, signature, status, created_at
FROM t_package
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPackagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPackagesRow struct {
	PackageID   string    `json:"package_id"`
	ProductCode string    `json:"product_code"`
	Version     string    `json:"version"`
	FileHash    string    `json:"file_hash"`
	Signature   string    `json:"signature"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]ListPackagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPackages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesRow{}
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.PackageID,
			&i.ProductCode,
			&i.Version,
			&i.FileHash,
			&i.Signature,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseTasks = `-- name: ListReleaseTasks :many
SELECT rt.task_id, rt.package_id, rt.target_group, rt.product_model,
       rt.hardware_version, rt.failure_threshold, rt.state, rt.created_at,
       p.product_code, p.version
FROM t_release_task rt
LEFT JOIN t_package p ON rt.package_id = p.package_id
ORDER BY rt.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReleaseTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReleaseTasksRow struct {
	TaskID           string         `json:"task_id"`
	PackageID        string         `json:"package_id"`
	TargetGroup      string         `json:"target_group"`
	ProductModel     string         `json:"product_model"`
	HardwareVersion  string         `json:"hardware_version"`
	FailureThreshold string         `json:"failure_threshold"`
	State            string         `json:"state"`
	CreatedAt        time.Time      `json:"created_at"`
	ProductCode      sql.NullString `json:"product_code"`
	Version          sql.NullString `json:"version"`
}

func (q *Queries) ListReleaseTasks(ctx context.Context, arg ListReleaseTasksParams) ([]ListReleaseTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseTasksRow{}
	for rows.Next() {
		var i ListReleaseTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.PackageID,
			&i.TargetGroup,
			&i.ProductModel,
			&i.HardwareVersion,
			&i.FailureThreshold,
			&i.State,
			&i.CreatedAt,
			&i.ProductCode,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpgradeRecordsByTask = `-- name: ListUpgradeRecordsByTask :many
SELECT id, device_id, task_id, status, created_at
FROM t_upgrade_record
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListUpgradeRecordsByTaskRow struct {
	ID        int64     `json:"id"`
	DeviceID  string    `json:"device_id"`
	TaskID    string    `json:"task_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUpgradeRecordsByTask(ctx context.Context, taskID string) ([]ListUpgradeRecordsByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpgradeRecordsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpgradeRecordsByTaskRow{}
	for rows.Next() {
		var i ListUpgradeRecordsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.TaskID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageStatus = `-- name: UpdatePackageStatus :one
UPDATE t_package
SET status = $2
WHERE package_id = $1
RETURNING package_id, product_code, version, file_hash, signature, status, created_at
`

type UpdatePackageStatusParams struct {
	PackageID string `json:"package_id"`
	Status    string `json:"status"`
}

type UpdatePackageStatusRow struct {
	PackageID   string    `json:"package_id"`
	ProductCode string    `json:"product_code"`
	Version     string    `json:"version"`
	FileHash    string    `json:"file_hash"`
	Signature   string    `json:"signature"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) (UpdatePackageStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updatePackageStatus, arg.PackageID, arg.Status)
	var i UpdatePackageStatusRow
	err := row.Scan(
		&i.PackageID,
		&i.ProductCode,
		&i.Version,
		&i.FileHash,
		&i.Signature,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateReleaseTaskState = `-- name: UpdateReleaseTaskState :one
UPDATE t_release_task
SET state = $2
WHERE task_id = $1
RETURNING task_id, package_id, target_group, product_model, hardware_version, failure_threshold, state, created_at
`

type UpdateReleaseTaskStateParams struct {
	TaskID string `json:"task_id"`
	State  string `json:"state"`
}

type UpdateReleaseTaskStateRow struct {
	TaskID           string    `json:"task_id"`
	PackageID        string    `json:"package_id"`
	TargetGroup      string    `json:"target_group"`
	ProductModel     string    `json:"product_model"`
	HardwareVersion  string    `json:"hardware_version"`
	FailureThreshold string    `json:"failure_threshold"`
	State            string    `json:"state"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) UpdateReleaseTaskState(ctx context.Context, arg UpdateReleaseTaskStateParams) (UpdateReleaseTaskStateRow, error) {
	row := q.db.QueryRowContext(ctx, updateReleaseTaskState, arg.TaskID, arg.State)
	var i UpdateReleaseTaskStateRow
	err := row.Scan(
		&i.TaskID,
		&i.PackageID,
		&i.TargetGroup,
		&i.ProductModel,
		&i.HardwareVersion,
		&i.FailureThreshold,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO t_device (device_id, device_group, product_model, hardware_version, current_version, product_code)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (device_id)
DO UPDATE SET
  current_version = EXCLUDED.current_version,
  last_heartbeat = NOW(),
  product_code = EXCLUDED.product_code
RETURNING device_id, device_group, product_model, hardware_version, current_version, product_code, last_heartbeat, tags, registered_at
`

type UpsertDeviceParams struct {
	DeviceID        string `json:"device_id"`
	DeviceGroup     string `json:"device_group"`
	ProductModel    string `json:"product_model"`
	HardwareVersion string `json:"hardware_version"`
	CurrentVersion  string `json:"current_version"`
	ProductCode     string `json:"product_code"`
}

type UpsertDeviceRow struct {
	DeviceID        string          `json:"device_id"`
	DeviceGroup     string          `json:"device_group"`
	ProductModel    string          `json:"product_model"`
	HardwareVersion string          `json:"hardware_version"`
	CurrentVersion  string          `json:"current_version"`
	ProductCode     string          `json:"product_code"`
	LastHeartbeat   time.Time       `json:"last_heartbeat"`
	Tags            json.RawMessage `json:"tags"`
	RegisteredAt    time.Time       `json:"registered_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UpsertDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.DeviceID,
		arg.DeviceGroup,
		arg.ProductModel,
		arg.HardwareVersion,
		arg.CurrentVersion,
		arg.ProductCode,
	)
	var i UpsertDeviceRow
	err := row.Scan(
		&i.DeviceID,
		&i.DeviceGroup,
		&i.ProductModel,
		&i.HardwareVersion,
		&i.CurrentVersion,
		&i.ProductCode,
		&i.LastHeartbeat,
		&i.Tags,
		&i.RegisteredAt,
	)
	return i, err
}

const upsertUpgradeRecord = `-- name: UpsertUpgradeRecord :one
INSERT INTO t_upgrade_record (
  device_id,
  task_id,
  status
) VALUES (
  $1, $2, $3
)
ON CONFLICT (device_id, task_id)
DO UPDATE SET
  status = EXCLUDED.status,
  created_at = NOW()
RETURNING id, device_id, task_id, status, created_at
`

type UpsertUpgradeRecordParams struct {
	DeviceID string `json:"device_id"`
	TaskID   string `json:"task_id"`
	Status   string `json:"status"`
}

type UpsertUpgradeRecordRow struct {
	ID        int64     `json:"id"`
	DeviceID  string    `json:"device_id"`
	TaskID    string    `json:"task_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertUpgradeRecord(ctx context.Context, arg UpsertUpgradeRecordParams) (UpsertUpgradeRecordRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUpgradeRecord, arg.DeviceID, arg.TaskID, arg.Status)
	var i UpsertUpgradeRecordRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.TaskID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
